baseurl = "http://unlogic.co.uk/"
title = "Unlogic"
paginate = 5
disqusShortname="unlogic"
theme = "hugo-minimalist"

canonifyurls = true

# pygmentsuseclasses=false
# pygmentsstyle="fruity"

[author]
name = "Sven Steinbauer"

[permalinks]

page = "/:title"
post = "/:year/:month/:day/:title"

[params]
header_background="images/keyboard-feature.jpg"
header_title="Unlogic"
description="I have a keyboard, a compiler, and a whole load of luck"
author="Sven Steinbauer"
avatar="images/avatar.jpg"
copyright="Sven Steinbauer"

[social]
github="svenito"
twitter="binaryheadache"
highlight="molokai"
